!------------------------------------------------------------------------------
MODULE MOD_GRAPH_PAR

  INTEGER, PARAMETER :: NF_TOT1=500, NPAGE1=500

  TYPE GRAPH_PAGE
    INTEGER :: IDATE0(6), IDATEC(6), IPERIOD(4), NFIELD
    INTEGER, DIMENSION(:), ALLOCATABLE :: PRESENT_TYPE, NCONTOUR, IPALETTE, ILABFORMAT,&
! PRESENT_TYPE: 1 - color filling, 2 - isolines, 3 - symbols, 4 - wind barb, 5 - arrows 
 DISCIPL, CATEG, INDEX
    CHARACTER*1, DIMENSION(:), ALLOCATABLE :: FIELD_TYPE ! S - Scalar,
! U - horizontal component and V - vertica component of vectorial field component
    REAL, DIMENSION(:,:,:), ALLOCATABLE :: FIELD
    REAL, DIMENSION(:,:), ALLOCATABLE :: CONTOUR_VAL
    CHARACTER*120, DIMENSION(10) :: ACOMMENT
    CHARACTER*60, DIMENSION(:), ALLOCATABLE :: NAME_PAR, NAME_LEV
    INTEGER, DIMENSION(:), ALLOCATABLE :: NCHAR_NAME_PAR, NCHAR_NAME_LEV
    CHARACTER :: APAGE*4
    INTEGER :: NX_CROSS
    REAL :: LON_CROSS_INI, LON_CROSS_FIN, LAT_CROSS_INI, LAT_CROSS_FIN
  END TYPE GRAPH_PAGE

  REAL :: DX, DY, X0, Y0, X00, Y00, XNN, YNN, VALMISS=-9999., PI

  INTEGER :: NX, NY, NPAGE, IFLAG_GEO, IMODEL_CODE, VERT_COORD_TYPE

  TYPE (GRAPH_PAGE), DIMENSION(NPAGE1) :: PAGE

  REAL, DIMENSION(:,:), ALLOCATABLE :: LSM, ALON, ALAT
  REAL, DIMENSION(:), ALLOCATABLE :: VERT_COORD

  INTEGER :: ISTEREO, IDEV_TYPE, IFL_LINE(10)=0, IFL_MAP=1
  REAL :: STEREOLAT0, STEREOLON0, STEREORAD, STEREOLATN, XZOOM_INI, XZOOM_FIN, YZOOM_INI, YZOOM_FIN

  CHARACTER(LEN=60) :: NAME_VERT_COORD

END MODULE MOD_GRAPH_PAR
!------------------------------------------------------------------------------
MODULE MOD_GRAPH_PAR_DEF
  INTEGER :: INDPAGE, NFL, INDFL, GRAFTYPE, NCONT, COLORPAL, INDFORMAT, TYPECONTDEF, ISMOOTH
  CHARACTER*1 :: ATYPE
  REAL, DIMENSION(30) :: CONTDEF
  CHARACTER (LEN=120) :: TITLE_DEF
 
  NAMELIST /GRAPH_DEF/ INDPAGE, NFL, INDFL, GRAFTYPE, NCONT, COLORPAL, INDFORMAT, TYPECONTDEF, ATYPE, CONTDEF, TITLE_DEF, ISMOOTH

END MODULE MOD_GRAPH_PAR_DEF
!------------------------------------------------------------------------------
