#! /bin/bash

export NNODE=4
export NPROC_NODE=16
export INIDATE="2020122800"
export HRUN=3
export HRESTART=0
export DHINPUT=3
export DHOUTPUT=1
export DHOUTPUT_SHF=1
export DIROUTPUT_MHF="/data/strade/moloch/mhf"
export DIROUTPUT_SHF="/data/strade/moloch/shf"
export HOUR_LIMIT=6
export MODEL_LOWER="moloch"
export FILE_FLAG_MODEL_RUN_FINISH="../../moloch_run_finish.txt"
export FILE_FLAG_MODEL_RUN_ERROR="../../moloch_run_error.txt"

nohup ./moloch_run.script 1>stout 2>&1 &

